### YamlMime:ManagedReference
items:
- uid: System.Data.Linq.ChangeConflictException
  id: ChangeConflictException
  children:
  - System.Data.Linq.ChangeConflictException.#ctor
  - System.Data.Linq.ChangeConflictException.#ctor(System.String)
  - System.Data.Linq.ChangeConflictException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ChangeConflictException
  nameWithType: ChangeConflictException
  fullName: System.Data.Linq.ChangeConflictException
  type: Class
  summary: "Gegenereerd lezen wanneer een update is mislukt omdat de databasewaarden zijn bijgewerkt sinds de client laatste."
  remarks: "Het volgende voorbeeld ziet hoe deze uitzondering kan worden gebruikt voor het retourneren van gegevens over een conflict gelijktijdigheid van taken."
  example:
  - >-
    [!code-cs[System.Data.Linq.ObjectChangeConflict#1](~/add/codesnippet/csharp/objconflict/program.cs#1)]
     [!code-vb[System.Data.Linq.ObjectChangeConflict#1](~/add/codesnippet/visualbasic/objconflict/module1.vb#1)]
  syntax:
    content: 'public class ChangeConflictException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Linq.ChangeConflictException.#ctor
  id: '#ctor'
  parent: System.Data.Linq.ChangeConflictException
  langs:
  - csharp
  name: ChangeConflictException()
  nameWithType: ChangeConflictException.ChangeConflictException()
  fullName: System.Data.Linq.ChangeConflictException.ChangeConflictException()
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Data.Linq.ChangeConflictException&quot;> </xref> klasse."
  syntax:
    content: public ChangeConflictException ();
    parameters: []
  overload: System.Data.Linq.ChangeConflictException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ChangeConflictException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Data.Linq.ChangeConflictException
  langs:
  - csharp
  name: ChangeConflictException(String)
  nameWithType: ChangeConflictException.ChangeConflictException(String)
  fullName: System.Data.Linq.ChangeConflictException.ChangeConflictException(String)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Data.Linq.ChangeConflictException&quot;> </xref> klasse en geeft u een bericht waarin wordt uitgelegd van de uitzondering."
  syntax:
    content: public ChangeConflictException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht worden weergegeven wanneer de uitzondering is opgetreden."
  overload: System.Data.Linq.ChangeConflictException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ChangeConflictException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Data.Linq.ChangeConflictException
  langs:
  - csharp
  name: ChangeConflictException(String,Exception)
  nameWithType: ChangeConflictException.ChangeConflictException(String,Exception)
  fullName: System.Data.Linq.ChangeConflictException.ChangeConflictException(String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Data.Linq.ChangeConflictException&quot;> </xref> klasse, geeft u een bericht waarin wordt uitgelegd van de uitzondering en Hiermee geeft u de uitzondering dat deze uitzondering heeft veroorzaakt."
  syntax:
    content: public ChangeConflictException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht worden weergegeven wanneer de uitzondering is opgetreden."
    - id: innerException
      type: System.Exception
      description: "Hiermee geeft u de uitzondering die <xref href=&quot;System.Data.Linq.ChangeConflictException&quot;> </xref> is een resultaat."
  overload: System.Data.Linq.ChangeConflictException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Data.Linq.ChangeConflictException.#ctor
  parent: System.Data.Linq.ChangeConflictException
  isExternal: false
  name: ChangeConflictException()
  nameWithType: ChangeConflictException.ChangeConflictException()
  fullName: System.Data.Linq.ChangeConflictException.ChangeConflictException()
- uid: System.Data.Linq.ChangeConflictException.#ctor(System.String)
  parent: System.Data.Linq.ChangeConflictException
  isExternal: false
  name: ChangeConflictException(String)
  nameWithType: ChangeConflictException.ChangeConflictException(String)
  fullName: System.Data.Linq.ChangeConflictException.ChangeConflictException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Linq.ChangeConflictException.#ctor(System.String,System.Exception)
  parent: System.Data.Linq.ChangeConflictException
  isExternal: false
  name: ChangeConflictException(String,Exception)
  nameWithType: ChangeConflictException.ChangeConflictException(String,Exception)
  fullName: System.Data.Linq.ChangeConflictException.ChangeConflictException(String,Exception)
- uid: System.Data.Linq.ChangeConflictException.#ctor*
  parent: System.Data.Linq.ChangeConflictException
  isExternal: false
  name: ChangeConflictException
  nameWithType: ChangeConflictException.ChangeConflictException
