### YamlMime:ManagedReference
items:
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  id: ForeignKeyReferenceAlreadyHasValueException
  children:
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException
  nameWithType: ForeignKeyReferenceAlreadyHasValueException
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  type: Class
  summary: "Hiermee geeft u de fouten die zich voordoen wanneer wordt geprobeerd een refererende sleutel wijzigen wanneer de entiteit is al geladen."
  syntax:
    content: 'public class ForeignKeyReferenceAlreadyHasValueException : InvalidOperationException'
  inheritance:
  - System.InvalidOperationException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  id: '#ctor'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException()
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref> klasse met een systeem geleverd bericht met een beschrijving van de fout."
  remarks: "Deze constructor initialiseert de <xref:System.Exception.Message%2A>eigenschap van het nieuwe exemplaar voor een systeem geleverd bericht met een beschrijving van de fout, zoals &quot;DefaultMessageDisplayedByParameterlessCtorWriterMustSupply&quot;.</xref:System.Exception.Message%2A> Dit bericht wordt rekening gehouden met de huidige systeemcultuur.       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.InsufficientMemoryException>.</xref:System.InsufficientMemoryException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De gelokaliseerde fouttekenreeks bericht. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException ();
    parameters: []
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException(String)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref> klasse met een opgegeven bericht met een beschrijving van de fout."
  remarks: "De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>.</xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht opgegeven in `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de uitzondering wordt beschreven. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks gelokaliseerd voor de huidige systeemcultuur."
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref> klasse met een opgegeven foutbericht en een verwijzing naar de interne uitzondering dat de oorzaak van deze uitzondering."
  remarks: "Een uitzondering die is gegenereerd als direct resultaat van een eerdere uitzondering moet een verwijzing bevatten naar de vorige uitzondering in de <xref:System.Exception.InnerException%2A>eigenschap.</xref:System.Exception.InnerException%2A> De <xref:System.Exception.InnerException%2A>eigenschap dezelfde waarde die is doorgegeven aan de constructor of `null` als de <xref:System.Exception.InnerException%2A>eigenschap levert niet de waarde van de binnenste uitzondering voor de constructor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>.</xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht opgegeven in `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de uitzondering wordt beschreven. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks gelokaliseerd voor de huidige systeemcultuur."
    - id: innerException
      type: System.Exception
      description: "De uitzondering die de oorzaak van de huidige uitzondering. Als de `innerException` parameter is niet <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, de huidige uitzondering is opgetreden tijdens een <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blok die verantwoordelijk is voor de interne uitzondering."
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.InvalidOperationException
  isExternal: false
  name: System.InvalidOperationException
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException()
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException(String)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException
