### YamlMime:ManagedReference
items:
- uid: System.ExecutionEngineException
  id: ExecutionEngineException
  children:
  - System.ExecutionEngineException.#ctor
  - System.ExecutionEngineException.#ctor(System.String)
  - System.ExecutionEngineException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ExecutionEngineException
  nameWithType: ExecutionEngineException
  fullName: System.ExecutionEngineException
  type: Class
  summary: "De uitzondering die wordt gegenereerd wanneer er een interne fout in de engine voor het uitvoeren van de common language runtime is. Deze klasse kan niet worden overgenomen."
  remarks: "Er is geen niet-verouderde VARIANT naar ExecutionEngineException. Als de uitvoering van uw toepassing kan niet verder worden aanhoudend, gebruikt u de <xref:System.Environment.FailFast%2A>methode.</xref:System.Environment.FailFast%2A>"
  syntax:
    content: >-
      [System.Obsolete("This type previously indicated an unspecified fatal error in the runtime. The runtime no longer raises this exception so this type is obsolete.")]

      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class ExecutionEngineException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ExecutionEngineException.#ctor
  id: '#ctor'
  parent: System.ExecutionEngineException
  langs:
  - csharp
  name: ExecutionEngineException()
  nameWithType: ExecutionEngineException.ExecutionEngineException()
  fullName: System.ExecutionEngineException.ExecutionEngineException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ExecutionEngineException&quot;> </xref> klasse."
  remarks: "Deze constructor initialiseert de <xref:System.Exception.Message%2A>eigenschap van het nieuwe exemplaar op een systeem geleverd bericht die de fout wordt beschreven, zoals &quot;interne fout opgetreden.&quot;</xref:System.Exception.Message%2A> Dit bericht wordt rekening gehouden met de huidige systeemcultuur.       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.ExecutionEngineException>.</xref:System.ExecutionEngineException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Een null-verwijzing (`Nothing` in Visual Basic). |   | <xref:System.Exception.Message%2A>| De gelokaliseerde fouttekenreeks bericht. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ExecutionEngineException ();
    parameters: []
  overload: System.ExecutionEngineException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ExecutionEngineException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ExecutionEngineException
  langs:
  - csharp
  name: ExecutionEngineException(String)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ExecutionEngineException&quot;> </xref> klasse met een opgegeven foutbericht."
  remarks: "Deze constructor initialiseert de <xref:System.Exception.Message%2A?displayProperty=fullName>eigenschap van de nieuwe uitzondering via de `message` parameter.</xref:System.Exception.Message%2A?displayProperty=fullName> De inhoud van `message` is bedoeld om te worden ge√Ønterpreteerd door mensen. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks voor de huidige systeemcultuur gelokaliseerd.       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.ExecutionEngineException>.</xref:System.ExecutionEngineException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Een null-verwijzing (`Nothing` in Visual Basic). |   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ExecutionEngineException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Het bericht dat de fout wordt beschreven."
  overload: System.ExecutionEngineException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ExecutionEngineException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.ExecutionEngineException
  langs:
  - csharp
  name: ExecutionEngineException(String,Exception)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String,Exception)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.ExecutionEngineException&quot;> </xref> klasse met een opgegeven foutbericht en een verwijzing naar de interne uitzondering dat de oorzaak van deze uitzondering."
  remarks: "Een uitzondering die is gegenereerd als direct resultaat van een eerdere uitzondering moet een verwijzing bevatten naar de vorige uitzondering in de <xref:System.Exception.InnerException%2A>eigenschap.</xref:System.Exception.InnerException%2A> De <xref:System.Exception.InnerException%2A>eigenschap dezelfde waarde die is doorgegeven aan de constructor of een null-verwijzing (`Nothing` in Visual Basic) als de <xref:System.Exception.InnerException%2A>eigenschap levert niet de waarde van de binnenste uitzondering voor de constructor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       De volgende tabel toont de eerste waarden voor een exemplaar van <xref:System.ExecutionEngineException>.</xref:System.ExecutionEngineException>      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| De verwijzing naar de interne uitzondering. |   | <xref:System.Exception.Message%2A>| De fouttekenreeks bericht. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ExecutionEngineException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Het foutbericht met uitleg over de reden voor de uitzondering."
    - id: innerException
      type: System.Exception
      description: "De uitzondering die de oorzaak van de huidige uitzondering. Als de `innerException` parameter is niet een null-verwijzing (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> in Visual Basic), de huidige uitzondering is opgetreden tijdens een <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blok die verantwoordelijk is voor de interne uitzondering."
  overload: System.ExecutionEngineException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.ExecutionEngineException.#ctor
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException()
  nameWithType: ExecutionEngineException.ExecutionEngineException()
  fullName: System.ExecutionEngineException.ExecutionEngineException()
- uid: System.ExecutionEngineException.#ctor(System.String)
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException(String)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ExecutionEngineException.#ctor(System.String,System.Exception)
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException(String,Exception)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String,Exception)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.ExecutionEngineException.#ctor*
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException
  nameWithType: ExecutionEngineException.ExecutionEngineException
